IF (WIN32)
	SET(AUDENC_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/plugins/audioEncoders/")
ELSE (WIN32)
	SET(AUDENC_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}/ADM_plugins/audioEncoders/")
ENDIF (WIN32)

MACRO(INIT_AUDIO_ENCODER _lib)
	INCLUDE_DIRECTORIES("${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_core/include"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_coreAudio/include"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_coreUI/include"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_audiofilter"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_plugin")
	ADD_DEFINITIONS("-DADM_MINIMAL_UI_INTERFACE")
	TARGET_LINK_LIBRARIES(${_lib} ADM_core)
ENDMACRO(INIT_AUDIO_ENCODER)

MACRO(INSTALL_AUDIOENCODER _lib)
	INSTALL(TARGETS ${_lib} DESTINATION "${AUDENC_INSTALL_DIR}")
ENDMACRO(INSTALL_AUDIOENCODER)
