IF (WIN32)
	SET(VIDFLT_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/plugins/videoFilter/")
ELSE (WIN32)
	SET(VIDFLT_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}/ADM_plugins/videoFilter/")
ENDIF (WIN32)

MACRO(INIT_VIDEOFILTER_PLUGIN _lib)
    INCLUDE_DIRECTORIES(.
						"${AVIDEMUX_CORECONFIG_DIR}"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_core/include"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_coreUI/include"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_coreImage/include"
						"${AVIDEMUX_SOURCE_DIR}/avidemux/ADM_plugin")
ENDMACRO(INIT_VIDEOFILTER_PLUGIN)

MACRO(INSTALL_VIDEOFILTER _lib)
	TARGET_LINK_LIBRARIES(${_lib} ADM_core ADM_coreUI ADM_coreImage )
	INSTALL(TARGETS ${_lib} DESTINATION "${VIDFLT_INSTALL_DIR}")
ENDMACRO(INSTALL_VIDEOFILTER)
